### PR TITLE
Delete object #82

### PR DESCRIPTION
**Pull request by epii-1**
Solves #82

### CODE REVIEW

**Comment by keski** [comment]
I got the following error when attempting to delete an object with an interface field:
```json
"errors": [
    {
      "message": "collection or view not found: FriendsEdgeFromCharacter",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "deleteHuman"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: collection or view not found: FriendsEdgeFromCharacter",
            "    at executeTransaction (/Users/robke04/Documents/Git_projects/SPIRIT/woo.sh/generated-example-server/driver.js:1043:28)",
            "    at processTicksAndRejections (internal/process/task_queues.js:89:5)"
          ]
        }
      }
    }
  ],
  "data": {
    "deleteHuman": null
  }
}
```

I've updated the code to reflect the necessary changes.

@epii-1 Would you mind looking it over quickly before I merge?

**Comment by epii-1** [comment]
@keski Good catch! However, I don't think that change actually solves the issue properly. Instead the fields that leads to edge-interface needs to be identified and then the removal of all edges needs to be done for all edge-types implementing these edge-interfaces. 
Converted the PR to draft while I fix this.

**Comment by epii-1** [comment]
I think I overestimated how much where actually needed to correct this...

**Comment by keski** [comment]
I found that the code deleted a bit too freely on account of a field reference typo (source -> _from, target -> _to). I've corrected this in https://github.com/LiUGraphQL/woo.sh/pull/86/commits/2e0e229cc914e9325e253ee4127fc6641261337f. This should now be ready for merge.

**Pull request merged**
