### PR TITLE
Unions

### PR DESCRIPTION
**Pull request by epii-1**
@hartig @keski @rcapshaw I'm creating this PR as a draft early as I am requesting some feedback here.
This is an early, and quite, crude attempt to implement (type!) unions with some severe limitations.
~~I'm also enforcing #67 here to simplify things.~~
Fields of union type cannot be updated using update. Instead ´deleteEdge´ and ´createEdge´ should be used for these fields.

Unions can be used **only** if they only contain types. So no interfaces, no unions of unions, no scalars and no enums. Just regular types. The is currently nothing actually preventing a user for creating unions of other things than types, but I doubt it would give the expected results.

Fields of union type can not be queried deeper. I.e. only the id of the target(s) can be reached in a single query. To get the actual objects additional queries are required.

For creating new objects, unions behaves just as interfaces.

I currently have three questions:
1. ~~Should we allow unions containing interfaces? And unions containing unions?~~ No, following response.
2. ~~How should queries/gets behave for unions?~~ The question was unclear, but conditional fragment is the answer.
3. ~~Should we add additional fields for fields of union type, such that there is one field for each type possible in the union?~~ Conditional fragment are enough

PS: This is not properly tested yet.

### CODE REVIEW

**Comment by keski** [comment]
There is a way in which union/interfaces can be queried deeper using what is called "conditional fragments". For example, assume that we have the following DB schema:
```graphql
union Character = Droid | Human 

type Droid {
  serial_number: String!
}

type Human {
  name: String!
}
```

Now if we query `Character` by ID (assuming the same query types as for interfaces/objects) we could access deeper fields using the following query:
```graphql
query {
  character(id:"xxx/yyy"){
    __typename
    ... on Human {
      name
    }
    ... on Droid {
      serial_number
    }
  }
}
```

As far as I know, we basically just need to implement the `__resolveType` resolver for the union and then the framework will do the rest by piping the request to the existing resolvers for the regular types. This already works for interfaces.

With respects to the point above:

1. No. From the spec: `The member types of a Union type must all be Object base types; Scalar, Interface and Union types must not be member types of a Union. Similarly, wrapping types must not be member types of a Union.`
2. I think we should follow the same structure as for interfaces.
3. I think leveraging the conditional fragment structures should be enough.

@epii-1 @hartig @rcapshaw

**Comment by keski** [comment]
Related to #97

**Comment by epii-1** [comment]
I'll take a proper look at implementing conditional fragment then!

**Comment by hartig** [comment]
Just to record my opinion on the three questions raised by Leif (and already answered by Robin):
1. No. See Robin's answer.
2. We don't need to support querying based on union types (i.e., no query operations for union types).
3. Like Robin says, there is no need to add any fields. The use of fragments is the correct way for GraphQL queries to deal with union types.

**Comment by hartig** [comment]
Leif, in your initial comment you write: "I'm also enforcing #67 here to simplify things."  Is this really necessary? Bundling multiple things for different issues together in a single PR makes it difficult to keep track of which changes are for which issue. Moreover, it becomes problematic if one of the issues is about adding a new feature (which should not break existing client code) whereas another issue covered by the same PR is about a breaking change.

**Comment by hartig** [comment]
Leif, all, please do not forget to also include the corresponding entries to CHANGELOG.md into your PRs.

**Comment by epii-1** [comment]
Olaf, no it's not strictly necessary. But it does simplify things as we then don't have to implement things that will be removed later in any case. Another option would be to not enforce #67, but at the same time not implementing inline updates for fields of union type (This might actually still require some changes to how the deletion of edges is done in updates. I am not sure about that at this point). 

Good point about the changelog. I still have to make that a habit.

**Comment by hartig** [comment]
Leif, you propose:
>  Another option would be to not enforce #67, but at the same time not implementing inline updates for fields of union type.

I think that this option is a good compromise. Please do it.

**Comment by epii-1** [comment]
@keski @hartig I'm having a bit of an issue with fragments that I did not expect: 
I modified the `starwards-db` schema to also include the union `union PlanetAndSpecies = Planet | Species` and modified `starship` to use this union as follows:
``` graphQL
type Starship {
  name: String!
  length: Float
  style: PlanetAndSpecies
}
```
Everything works fine so far and I can create a starship and planet using
``` graphQL
mutation {
                createStarship(data: {
                    name: "test"
                    style: { createPlanet: {name: "planetName" }}
                    }) { id }}
```
But when I try to query this newly created starship I run into issues.
The following two queries:
```graphQL
query {
            starship(id : someid){
                name
                style {
                    ... on Species { name }
                }}}
```
and 
```graphQL
query {
            starship(id : someid){
                name
                style {
                    ... on Planet { name }
                }}}
```
works just fine each on their own and produces the expected results. But when I try to combine them to 
```graphQL
query {
            starship(id : someid){
                name
                style {
                    ... on Planet { name }
                    ... on Species { name }
                }}}
```
it does not work! I get an early 400 error as if the resolver does not understand the query. 
From my understanding this is how inline/conditional fragments should be used, and yet it fails.

Any ideas?

**Comment by hartig** [comment]
I didn't look at the code. So, I cannot say what is causing this error. However, I just wanted to confirm that this last query (with the two inline fragments) is exactly the way how inline fragments are intended to be used. In other words, the query is correct and should work.

**Comment by epii-1** [comment]
I did similar tests for interfaces with almost the same results as for unions and opened this as a separate issue in #103 . One that one is resolved, this PR will hopefully be working and ready for review.

**Comment by keski** [comment]
The issue with the example above is related to the expected output field types. The query
```graphql
query {
  starship(id: "someid") {
    name
    style {
      ... on Planet {
        name
      }
      ... on Species {
        name
      }
    }
  }
}

```
assigns to the output field `name` either `String!` (required for `Planet`) or `String` (nullable for `Species`), but the field type needs to one of these. Basically, the problem comes down to the field name collision, so if we just apply an alias all should be fine. E.g.:
```graphql
query {
  starship(id: "someid") {
    name
    style {
      ... on Planet {
        planetName: name
      }
      ... on Species {
        speciesName: name
      }
    }
  }
}
```

**Comment by epii-1** [comment]
Somehow I managed to miss you comment Robin.

But when tested what you suggested it... work? But not really now I would expect it to work.

This is the result:
``` graphQL
starship: {
    name: 'test',
    style: {
      planetName: 'planetName',
      __typename: 'Planet',
      speciesName: 'planetName'
    },
    __typename: 'Starship'
  }
```
As you can see we get both `planetName` and `speciesName` from the same object.

**Comment by epii-1** [comment]
My last comment seams to still be an issue and I'm quite baffled by it. 

Any ideas @keski ?

**Comment by keski** [comment]
I just tried:
```graphql
mutation {
  createStarship(data: {
    name: "test",
    style: {
      createPlanet: {
        name: "planetName"
      }
    }
  }) {
    id
  }
}
```
```json
{
  "data": {
    "createStarship": {
      "id": "Starship/2859288"
    }
  }
}
```
followed by:
```graphql
query {
  starship(id: "Starship/2859288") {
    name
    style {
      ... on Species {
        nameForSpecies: name
      }
      ... on Planet {
        nameForPlanet: name
      }
    }
  }
}
```
```json
{
  "data": {
    "starship": {
      "name": "test",
      "style": {
        "nameForPlanet": "planetName"
      }
    }
  }
}
```

So, no problem for me following your last commit.

**Comment by epii-1** [comment]
I deleted everything, rebuilt and tested again myself, and yes it works as expected in the playground. But not when I run it as a client test. Might be worth keeping in mind for future tests.

With that out of the way, unless Robin find some other bugs with this, should we merge this before the next release? @hartig @rcapshaw

**Comment by hartig** [comment]
@keski did you manage to check this again?

**Pull request merged**
