### PR TITLE
Get Edge by ID and Update Edges #35

### PR DESCRIPTION
**Pull request by epii-1**
Implements updating annotation data of edges, and querying of edges by ID.

Again this should be squashed before merging as the annotation-filter commits appear here now again.

### CODE REVIEW

**Comment by hartig** [comment]
Robin, Leif, something is fishy here. According to [the diff](https://github.com/LiUGraphQL/woo.sh/pull/93/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1e), this PR modifies existing (!) entries in CHANGELOG.md -- even worse, these existing entries are for an already released version! The PR was merged on July 28 but the CHANGELOG entries in this PR are all for a version released on June 23. Can you please fix the CHANGELOG so that it correctly reflects what was released in the previous version and what was added later.

**Comment by epii-1** [comment]
I think I know what happened: At the start I added the implementation of the edge annotations one by one. But at either the last or second to last annotation related update, I squashed the changes into one line to prevent cluttering the changelog. After all, all the changes were related and simplifying it to stating "implemented annotations" made sense. Then the release happened before the last PR got merged, which cause this unintended changelog-mess.

I'll take a look at what change actually happened when.

**Comment by hartig** [comment]
Ah! That explains it.

Yes, please modify the CHANGELOG to separate the entries about changes that went into the release from the ones that came later.

In general, I am fine with merging several related changes into a single CHANGELOG entry, as long as they belong to the same release and the related issues (or PRs) are all referenced.

**Comment by epii-1** [comment]
The changelog should now, hopefully, be corrected, and updated for everything currently implemented.

**Comment by hartig** [comment]
Hi Leif, Thanks for updating the changelog!!

**Pull request merged**
