### PR TITLE
Implementing filtering on edge types #32

### PR DESCRIPTION
**Pull request by epii-1**
Solves #32 
(Try to squish and merge this when merging as there are some commits that does not need to be in the master branch)

### CODE REVIEW

**Comment by keski** [comment]
I noticed a bug when attempting to compile a schema where the outgoing edge of a type is inherited from an interface:
```
TypeError: Interface field argument Character._outgoingFriendsEdges(filter:) expects type
_FilterForFriendsEdgeFromCharacter but Human._outgoingFriendsEdges(filter:) is type _FilterForFriendsEdgeFromHuman.
```

For example,
```graphql
interface Character {
  name: String!
  friends: [Character]
}

type Human implements Character {
  name: String!
  friends: [Character]
}
```

Will generate:
```graphql
interface Character {
  name: String!
  friends(filter: _FilterForCharacter): [Character]
  id: ID!
  _friendsFromCharacter(filter: _FilterForCharacter): [Character]
  _friendsFromHuman(filter: _FilterForHuman): [Human]
  _outgoingFriendsEdges(filter: _FilterForFriendsEdgeFromCharacter): [_FriendsEdgeFromCharacter] # This is the issue!
  _creationDate: DateTime!
  _lastUpdateDate: DateTime
}

type Human implements Character {
  name: String!
  friends(filter: _FilterForCharacter): [Character]
  id: ID!
  _friendsFromCharacter(filter: _FilterForCharacter): [Character]
  _friendsFromHuman(filter: _FilterForHuman): [Human]
  _incomingFriendsEdgeFromCharacter(filter: _FilterForFriendsEdgeFromCharacter): [_FriendsEdgeFromCharacter]
  _outgoingFriendsEdges(filter: _FilterForFriendsEdgeFromHuman): [_FriendsEdgeFromHuman] # Does not match above!
  _incomingFriendsEdgeFromHuman(filter: _FilterForFriendsEdgeFromHuman): [_FriendsEdgeFromHuman]
  _creationDate: DateTime!
  _lastUpdateDate: DateTime
}
 # [... more]
```

Is there any particular reason why the ` _outgoingFriendsEdges` field does not also include the source type? E.g. ` _outgoingFriendsEdgesFromHuman`?

@epii-1 @hartig @rcapshaw

**Comment by epii-1** [comment]
Robin, I think I implemented it like that without reflecting over it because of how the field related to the edge looks like. It, to me at least, feels redundant to point out that the edge comes from a Human object, in this case, when we already clearly are in the human object. It would also get strange when we access interfaces as multiple fields would then be needed. But then again, we already have multiple fields for this reason in other places.

For the actual error, I guess that it's an issue of `_FilterForFriendsEdgeFromHuman` not implementing `_FilterForFriendsEdgeFromCharacter`, as the actual edge type should implement the edge interface already? At the same time input types can't actually implement interfaces, so this gets a bit more complicated. 
Quite strange that I never encountered that issue when testing on the spirit schema. (I had to double check. There are no types with fields with `[interface]` in spirit.)

**Comment by keski** [comment]
Right, interfaces aren't supported for input types, and it doesn't seem like it will be supported in future versions either from what I understand. If there's no reason for not using the more verbose format (i.e., include `FromX` suffix), I think we should go with that since it solves the problem in a straightforward way. Although it feels a bit redundant at least we end up with a symmetric solution. It will also only happen if the interface field references an interface while the implementing type references another type.

@epii-1

**Comment by keski** [comment]
I noticed some strange behavior when running the `getFilter` function, and the resulting query seemed to contain errors. @epii-1 do you recognize this?

After some digging, I found that this is probably related to how we reference the `alias` and field `i`. `getFilters` is one of the functions that has existed in a couple of versions already, but I think that this one, where the alias can be defined in the input, is the nicest. Rather than referencing the field in the AQL string I've therefore updated the function to use  the AQL helper function ` aql.literal(...)`, which basically inputs the variable as is into the query, rather than adding new variables. I have these changes locally for now, but if you're fine with these changes I'll push it to the `annotations-filter` branch.

**Comment by epii-1** [comment]
Considering we have had problem with the aliasing before (as we removed it again after I tried to implement it the first time), if you have a neater solution / a way to solve it, by all means, go for it. As it turned out to be "necessary" for the edge filtering as we use other variables than `x` there, we need the aliasing to work properly for this.

**Comment by epii-1** [comment]
Robin, I also changed how and what outgoing edges are added now. So the error should now be fixed.

**Comment by keski** [comment]
Squashed and merged from command line. Closing.

**Pull request closed without merging**
