### PR TITLE
Edge requesting for #31

### PR DESCRIPTION
**Pull request by epii-1**
Querying edges (including annotations) is now possible. 
Client-test should now work with annotations (hence the change to generation-tools).
Old edgeFields have internally been renamed edgeFieldEndpoints, and edgeFields are now used for fields containing incoming/outgoing edges (instead of the source/target of an edge) (edge_objects and edge_types in utils. Should maybe change that?).
Note that resolvers for list and updates of types starting with '_' is currently fully disabled (should only affect edges), as this is a separate issue.

@hartig want to take a look if you think there is something missing (if you got the time during all the grading), or should we ask @keski to review?

### CODE REVIEW

**Comment by epii-1** [comment]
@hartig, I realized I might have missed/forgotten something: currently it is not possible to query edges by ID (i.e. querying specific edges). It is instead only possible to query edges indirectly by querying their sources/targets, as described in https://github.com/LiUGraphQL/woo.sh/wiki/Overview-of-the-Approach#4-additional-fields-and-types-for-edges. Is the option to query specific edges something we want? I can find no mentions of it mentioned anywhere, so I assume it is not? But I prefer to double check anyway.

**Comment by hartig** [comment]
I have looked at this PR now. It looks okay to me. @keski what do you say?

**Comment by keski** [comment]
Since this is a new feature and 'master' is frozen for the time being, I'd suggest cancelling this merge request, and instead adapting it for merging directly with 'develop'. I can create a new branch and transfer all the things related to the `graphql-api-generator` and `graphql-resolver-generator`. Then we manually add the `graphql-server` related changes before issuing a new merge request based on this new branch.

Is this okay with everyone?

@epii-1 @hartig @rcapshaw

**Comment by hartig** [comment]
The idea was to have this PR merged before going into the freeze. However, if you feel it is easier to adapt the changes of this PR into your development branch, then that's fine with me. I just don't want the effort that Leif has spent on this to go to waste.

**Comment by epii-1** [comment]
I had expected to have to do the modifications needed to make these changes/this PR fit (I forgot the correct word in both Swedish and English...) with the new develop-branch in any case. So for me it does not matter if we merge this to master first, or if we add it straight to develop.

**Comment by hartig** [comment]
Thanks Leif.

In this case, let's do it as Robin proposes. Let's add these changes directly into the development branch.

However, I suggest we keep this PR open until everything has been carried over into the development branch.

**Comment by keski** [comment]
Sounds good, let's keep it open. @epii-1, do you want me to create the branch suggested above or do you want to do it?

**Comment by epii-1** [comment]
I'll do it. Just finished the last thing I worked with in any case.

**Pull request merged**
