### PR TITLE
DateTime (and Date) filters

### PR DESCRIPTION
**Pull request by epii-1**
Added requested DateTime-filters. 

There are some (code) changes to Date-filters in here that should be removed later, when the Date scalar is scraped. These changes should make no difference in practice thought. They where simply added from a now "deprecated" request. I'm letting them through anyway for now (they should all be marked with a TODO)

@hartig

### CODE REVIEW

**Comment by hartig** [comment]
Thanks Leif!!

@keski To me this looks good. Can you please double check and merge this PR.

**Comment by keski** [comment]
I've made some changese to make the process a bit more consistent with the rest of the generator code. @epii-1 could you have a look to make sure I didn't mess anything up before I merge it?

The functionality should be the same as before. To simplify the generation of the date time fields, I moved down the function calls so that the edge types are generated first. I also removed the config flag for adding the Date scalar, since this is handled by default if the scalar is included in the DB schema.

@hartig @rcapshaw

**Comment by epii-1** [comment]
@keski Looks good to me.

The only very minor thing I can comment on is allowing dateTime to not be generated, even thought creationDate and/or lastUpdateDate is generated. But if the user decided to shot him/herself in the foot by setting to configs in such a way, that's not really our problem.

**Comment by hartig** [comment]
Thanks all for this one.

**Pull request merged**
