### PR TITLE
Make serverjs a module

### PR DESCRIPTION
**Pull request by keski**
Addresses issue #117

### CODE REVIEW

**Comment by keski** [comment]
I assigned this pull request to you Riley, just so we that we get an extra pair of eyes on this. The server is now exported as a module. In `app.js`, we call `makeServer` from `server.js` and pass it an options object. The schemas are read and resolvers loaded and passed as part of this options object, rather being passed to the server as file references. This means that for the tests, we'll now be able to pass inline definitions of both GraphQL API schemas and resolver functions, which should really make things a lot easier.

The server is run using either `node app.js` or `npm start` (recommended), so we'll need to update the dockerfile entrypoint once we decide to merge this.

To be able to run `client-tests.js` with the most recent SPIRIT schemas you'll first need to run `npm install` in the test directory (either in the generated server or directly in `graphql-server`), comment out the union references used in the jobs schema file, and finally disable directives testing.

@rcapshaw @hartig

**Review by rcapshaw — APPROVED** [review]
Looks good to me! Nothing stood out that I felt needed to be double-checked.

**Comment by keski** [comment]
@rcapshaw, I've made a bunch of updates to the API tests and fixed some bugs. Could you have another look before the merge?

**Comment by hartig** [comment]
That's been a long time coming. Thanks for your effort!

**Pull request merged**
